theme = "grae"

[editor]
trim-trailing-whitespace = true
insert-final-newline = true
end-of-line-diagnostics = "hint"
auto-format = true
scrolloff = 15
completion-replace = true
bufferline = "always"

[editor.auto-save.after-delay]
enable = true
timeout = 1000

[editor.soft-wrap]
enable = true

[editor.lsp]
snippets = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
"-" = "command_mode"
"A-f" = ":format"

[keys.insert.j]
k = "normal_mode"
"C-space" = "delete_word_backward"

[keys.normal.space]
x = ":buffer-close"
o = ":buffer-close-others"
